spring.application.name=break.time.reminder
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- Eigene Konfigurationen für die App ---
app.default-timer.name=Standard Pomodoro
app.default-timer.work-minutes=25
app.default-timer.break-minutes=5