spring.application.name=break.time.reminder
server.port=8080

# Lokale Konfiguration (Nutzt externen Render-PostgreSQL-Zugriff für deinen PC)
spring.datasource.url=jdbc:postgresql://dpg-daduhgv40ujc73d1s370-a.frankfurt-postgres.render.com/timer_db_bjmc
spring.datasource.username=timer_db_bjmc_user
spring.datasource.password=xsx1fhRid0dmhHRZZaqXGYWwYe6PXbfC
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Lokales JWT Secret
jwt.secret=lokaler_test_schluessel_fuer_jwt_signatur_12345
jwt.expiration=86400000

app.default-timer.name=Standard Pomodoro
app.default-timer.work-minutes=25
app.default-timer.break-minutes=5